import React from 'react';
import '@/style/CalendarSection.css'
import Header from "@/section/Header";
import DayCalendar from "@/section/DayCalendar";
import Footer from '@/section/Footer';

export const metadata = {
  title: "Makkal Calendar | Tamil Daily Calendar",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className='App'>
      <Header />
      <main className={`d-flex h-100 justify-content-center align-items-center my-4 `}>
        <div className='container-xl'>
          <DayCalendar />
        </div>
      </main>
      <Footer/>
    </div>
  );
}
